# Generated by Django 4.2 on 2023-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='matched_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
